#!/usr/bin/env python

import imp, os

# git meta project: gmp
import gmp.main

# Load the configuration file
config = imp.load_source("config", os.path.expanduser("~/.metagitrc"))

# Initialize a new repo manager
manager = gmp.main.RepoManager()

# Get all repository sets
for set_name in filter(lambda x: x.endswith("_repos"), dir(config)):
    manager.add_set(set_name[:-6], getattr(config, set_name))

# Run the command line interface
manager()

