The metagit project can be used to manage a huge amount of git (or any
similar distributed scm) repositories at once. For example clone all
your github repositories to a folder on your new shinny machine. The
Project is inspired by a article in the german LinuxMagazin 08/10 by
mschilli.

The configuration is located in the main python skript `metagit'. Edit
it so make it fit your needs. For more information on commands try
`pydoc gmp' to the python module documentation.

* A example session:
  
  #+begin_src bash  
$ metagit list metagit
+ (git:hub) git@github.com:stettberger/metagit.git --> /home/cip/2009/qy03fugy/github/metagit
$ `metagit cd metagit`
$ echo $PWD
/home/cip/2009/qy03fugy/github/metagit
#+end_src

  #+begin_src bash
$ metagit foreach metagit commit -a
cd /home/stettberger/github/metagit; git commit  -a
[master d6cb963] removed metagit on peer
 1 files changed, 0 insertions(+), 1 deletions(-)
#+end_src

  #+begin_src bash
$ metagit push metagit
[... push ...]
#+end_src

* Features
  - SSHDir Listing - find repos on a remote machine
    - With support for uploading Repos to this remote dir
  - Github Listing - find all your github repos
    - With support for uploading Repos to this remote dir
  - Gitorious Listing - find all youy Gitorius repos
  - SVNList - clone all your svn repositories with git svn
  -  Use different scm system at once
     The default is git, but hg does also work

   
